name: Clojure CI

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Refresh Joke
      run: lein run -m reddit-scraper.core
