name: Refresh Joke

on:
  schedule:
    - cron: "0 5 * * *"
      displayName: Daily joke update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Clojure code
      run: lein run -m reddit-scraper.core
 #   - name: Get joke artifact
 #     uses: actions/upload-artifact@v2
 #     with:
 #       name: joke
 #       path: joke.txt
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Ava Downey
        author_email: avasdowney@gmail.com
        message: 'Routine jokes update'
        add: 'joke.txt'
 #   - name: Upload joke artifact
 #     uses: actions/upload-artifact@v2
 #     with:
 #       name: assets-for-download
 #       path: downloads

  push:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger GitHub pages rebuild
      run: |
        curl -L --fail --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
          --header "Authorization: Bearer $USER_TOKEN"
      env:
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
