name: Refresh Joke

on:
  schedule:
    - cron: "0 5 * * *"
      displayName: Daily joke update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.1.java11'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.469'
    - name: Run Clojure code
      run: lein run -m reddit-scraper.core
    - name: Trigger GitHub pages rebuild
      run: |
        curl -L --fail --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
          --header "Authorization: Bearer $USER_TOKEN"
      env:
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Ava Downey
        author_email: avasdowney@gmail.com
        message: 'Routine jokes update'
        add: 'joke.txt'
